### ISSUE TITLE
[Bug] pi.alert stopped working

### ISSUE THREAD

**Issue by stanelie** [leiweibau/Pi.Alert#377]
Hello.
My Pi.Alert instance suddenly stopped working about 3 hours ago.
The last action I did was stop the scan, edit a device and restart the scan. I got no more alerts after that.

The pialert.1.log file shows the following : 

```
Pi.Alert v2024-08-24
---------------------------------------------------------
Executing user: stanelie

Scan Devices
    Timestamp: 2024-08-27 15:15:00

Scanning...
    arp-scan Method...
    arp-scan: One interface
    Pi-hole Method...
Traceback (most recent call last):
File "/home/stanelie/pialert/back/pialert.py", line 3590, in
    sys.exit(main())    
             ^^^^^^
File "/home/stanelie/pialert/back/pialert.py", line 96, in main
    res = scan_network()
         ^^^^^^^^^^^^^^
File "/home/stanelie/pialert/back/pialert.py", line 735, in scan_network
    copy_pihole_network()
File "/home/stanelie/pialert/back/pialert.py", line 913, in copy_pihole_network
    sql.execute ("DELETE FROM PiHole_Network")
sqlite3.OperationalError: attempt to write a readonly database
```
I do not know how to recover from this. Thoughts?
Thanks!

**Comment by leiweibau** [comment]
Are the file permissions of the database still correct?

It cannot be ruled out that the database may have been damaged by the constant write accesses by the scans and the web frontend. You have certainly activated the automatic backups. Have you restored one of the backed up versions? 

I have already implemented your request https://github.com/leiweibau/Pi.Alert/issues/360 so far, which should significantly reduce the write accesses via the frontend according to your statement. I will publish a new update in the next few days.

**Comment by stanelie** [comment]
I've clicked on the restore button and I got a confirmation message that the database had been restored.
However, I still get the `sqlite3.OperationalError: attempt to write a readonly database` error message, even after a complete reboot of the raspberry pi.

**Comment by stanelie** [comment]
I've managed to restore a previous database, and the scanning works again.
However, it dates back from before the implementation of the "presence" checkbox. Because of this, I get this error message when I try to edit a device : 
`no such column: dev_PresencePage`

Is there a way to re-run the database upgrade from when I upgraded pi.alert?

The file permissions on the database are correct.

**Comment by leiweibau** [comment]
Then this backup was before the update. Execute “pialert-cli update_db”.

**Comment by stanelie** [comment]
Even though I've stopped the scan 30 minutes ago, I am receiving this error message when I run "pialert-cli update_db" : 
`Error: stepping, attempt to write a readonly database (8)`

**Comment by leiweibau** [comment]
Test the following:
- navigate to the “pialert/back” directory
```
./pialert-cli disable_scan 60
```
- navigate to the “pialert/db” directory
```
sqlite3 pialert.db .dump > dump.sql
mv pialert.db pialert.org.db
sqlite3 pialert.db < dump.sql
sudo chown "$USER":www-data pialert.db
```

**Comment by stanelie** [comment]
The first pialert-cli gives out this error after the line `Configured Pi.Alert scans are disabled` : `Error: stepping, attempt to write a readonly database (8)`

The second part completed without issue (the dump and db recreate part.

Before enabling the scan, I tried to run the `./pialert-cli update_db` command, it failed with the same error message again.

`./pialert-cli enable_scan` yielded this message : 
```
...
Configured Pi.Alert scans are enabled
Error: stepping, attempt to write a readonly database (8)
```

**Comment by leiweibau** [comment]
Which files are in the pialert/dB directory? (ls-al)

**Comment by stanelie** [comment]
```

stanelie@pialert:~/pialert/db $ ls -la
total 14532
drwxrwxr-x 3 stanelie www-data    4096 Aug 28 14:25 .
drwxr-xr-x 9 stanelie stanelie    4096 Aug 24 12:22 ..
-rw-r--r-- 1 stanelie stanelie  978916 Aug 28 14:23 dump.sql
-rw-r--r-- 1 www-data www-data 7566962 Aug 28 10:32 GeoLite2-Country.mmdb
-rwxrwxr-x 1 stanelie www-data 1421312 Aug 28 14:25 pialert.db
-rw-r--r-- 1 www-data www-data  287499 Aug 27 15:15 pialertdb_20240827_191352.zip
-rw-r--r-- 1 stanelie stanelie 1421312 Aug 28 14:25 pialert.db.bak
-rwxrwxr-x 1 stanelie www-data 1679360 Aug 27 15:15 pialert.db.old
-rwxrwxr-x 1 stanelie stanelie   32768 Aug 28 15:20 pialert.db-shm
-rwxrwxr-x 1 www-data www-data       0 Aug 28 11:37 pialert.db-wal
-rw-r--r-- 1 www-data www-data    4732 Aug 28 12:53 pialert_journal_buffer
-rwxrwxr-x 1 stanelie www-data 1466368 Aug 28 11:37 pialert.org.db
drwxrwxr-x 2 stanelie www-data    4096 Aug 27 15:15 temp

```

**Comment by leiweibau** [comment]
delete these files
-rwxrwxr-x 1 stanelie stanelie   32768 Aug 28 15:20 pialert.db-shm
-rwxrwxr-x 1 www-data www-data       0 Aug 28 11:37 pialert.db-wal

**Comment by stanelie** [comment]
Yup,
That fixed it.

Is the WAL mode usefull at all? Would it be useful to disable it?

Thanks again!

**Comment by leiweibau** [comment]
> Is the WAL mode usefull at all?

Yes, the WAL mode allows the database to be readable while the database is being written to

> Would it be useful to disable it?

Absolutely not. The original project did not use this mode and this led to several error messages while using the frontend.

As already written, I will publish an update in the next few days, which will address 2 of your feature requests and should make your work with the tool a little easier.

**Comment by stanelie** [comment]
Amazing, thanks!
